name: my_environment
channels:
    - conda-forge
dependencies:
    - faunus=2
    - jupyterlab
    - matplotlib=3
    - notebook
    - numpy=1
    - pandas=1
    - python=3
    - ruff
    - scipy=1
 
